version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: eagleson
      WORDPRESS_DB_PASSWORD: mastercomposebrewingpipe
      WORDPRESS_DB_NAME: scrapbook
#     WORDPRESS_TABLE_PREFIX: wp_
#     WORDPRESS_CONFIG_EXTRA: |
#       define('WP_HOME', 'http://localhost:8014');
#       define('WP_SITEURL', 'http://localhost:8014');
    volumes:
      - ./:/var/www/html/
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: scrapbook
      MYSQL_USER: eagleson
      MYSQL_PASSWORD: mastercomposebrewingpipe
      MYSQL_ROOT_PASSWORD: mastercomposebrewingpipe
#     MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
volumes:
  db: