version: "3.9"
volumes:
  frasierbot:
services:
  bot:
    build: ./bot
    expose: 
      - "1433"
    ports:
      - "1433:1433"
    volumes:
      - frasierbot:/var/opt/mssql/data
      - ./bot/src:/usr/src/app/src
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DOMAIN: ${DB_DOMAIN}
      DB_NAME: ${DB_NAME}
      SA_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: sqlserver://${DB_DOMAIN}:1433;database=${DB_NAME};user=${DB_USERNAME};password=${DB_PASSWORD};trustServerCertificate=true
      BOT_TOKEN: ${BOT_TOKEN}
      NODE_ENV: ${NODE_ENV}
      DELETE_MESSAGES: ${DELETE_MESSAGES}
      ACCEPT_EULA: Y

