export const HELP_MESSAGE = [
    "\n",
    "I'm listening...",
    "\n",
    "Use the following terms, separated by spaces:",
    "*1st:* **!F** or **!FRASIERBOT**",
    "*2nd:* **LEARN** or **FORGET**",
    "*3rd*: **NOUN (N)** or **ADJECTIVE (ADJ)** or **VERB (V)** or **ADVERB (ADV)** or **CHARACTER (C)** or **PLACE (P)** or **EXCLAMATION (E)** OR **QUOTE (Q)**",
    "*4th*: The term you want to add.  Terms can be multiple words, or you can add multiple different terms by separating with double &&",
    'e.g. **!FRASIERBOT learn noun ass milk**',
    "e.g. **!F learn adjective overpriced**",
    "e.g. **!F forget noun sherry**",
    "e.g. **!F learn verb run && walk**",
    "\n",
    "You can also view a list of all terms:",
    "e.g.: **!FRASIERBOT list noun**",
    "e.g.: **!FRASIERBOT list quote**",
    "\n",
    "To create a plot with random elements use curly braces.:",
    "Input.: **Niles went to his {noun_plural} and ordered some {adj} {noun}.**",
    "Output.: **Niles went to his wine clubs and ordered some overpriced ass milk.**",
    "\n",
    "Modifiers can be added to the end of noun and verb:",
    "**noun** or **n**",
    "**noun_plural** or **np**",
    "**verb** or **v**",
    "**verb_infinitive** or **vi** (walk)",
    "**verb_gerund** or **vg** (walking)",
    "**verb_past** or **vpa** (walked)",
    "**verb_present** or **vpr** (walks)",
    "**verb_future** or **vf** (will walk))",
    "\n",
    "You can number nouns, characters and places to create a continuous story about the same topic:",
    "I like {noun1} more than {noun2}. To summarize: {n1} is the best, {n2} sucks.",
    "\n",
    "You can tell Frasier to ignore what you are writing (if you want to paste a template):",
    "Include **!f ignore** or **!frasierbot ignore** anywhere in your message",
    "\n",
  ]