export const HELP_MESSAGE = [
    "\n",
    "I'm listening...",
    "\n",
    "Use the following terms, separated by spaces:",
    "*1st:* **!F** or **!FRASIERBOT**",
    "*2nd:* **LEARN** or **FORGET**",
    "*3rd*: **NOUN** or **ADJECTIVE** or **VERB** or **ADVERB** or **CHARACTER**",
    "*4th*: The term you want to add.  Use double quotes for multi-word.",
    'e.g. **!FRASIERBOT learn noun "ass milk"**',
    "e.g. **!F learn adjective overpriced**",
    "e.g. **!F forget noun sherry**",
    "\n",
    "You can also view a list of all terms:",
    "e.g.: **!FRASIERBOT list noun**",
    "\n",
    "To create a plot with random elements use curly braces.:",
    "Input.: **Niles went to the {noun} and ordered some {advective} {noun}.**",
    "Output.: **Niles went to the wine club and ordered some overpriced ass milk.**",
    "\n",
  ]